security:
    encoders:
          App\Domain\Models\User:
                algorithm: bcrypt

    providers:
        our_db_provider:
                    entity:
                        class: App\Domain\Models\User
                        property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            guard:
                authenticators:
                    - App\UI\Action\Security\UserAuthenticationGuard

            anonymous: ~
            logout_on_user_change: true
            provider: our_db_provider
            logout:
                path: logout
                target: index

    access_control:
#         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/, roles: ROLE_USER }

