App\Domain\DTO\AddCommentOnArticleDTO:
    properties:
        email:
            - Email:
                message: Cet email "{{value}} n'est pas au bon format.
                checkMX: true
        content:
            - Length : { min: 4, minMessage: 'minimum 4 caractères', groups: ['add_comment'] }
            - NotBlank: ~
        lastname:
            - Length: { min: 4, minMessage: 'Nombre de caractères compris entre 4 et 50', max: 50, maxMessage: 'Nombre de caractères compris entre 4 et 50', groups: ['add_comment'] }
            - NotBlank: ~
