#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    defaults:
        _controller: App\Controller\MainController::index

aboutme:
    path: /aboutme
    defaults:
        _controller: App\Controller\AboutMeController::show

faq:
    path: /faq
    defaults:
        _controller: App\Controller\Front\FaqController::show

photos:
    path: /photos/{page}
    defaults:
        page: 1
        _controller: App\Controller\PortfolioController::list
    requirements:
        page: '\d+'

informations:
    path: /infos
    defaults:
        _controller: App\Controller\InformationsController::show

clients:
    path: /clients
    defaults:
        _controller: App\Controller\CustomersController::list

contact_sucess:
    path: /
    defaults:
        _controller: App\Controller\MainController::index

#admin:
#    path: /admin
#    defaults:
#        _controller: App\Controller\Admin\AdminController::show

adminLogin:
    path: /login
    defaults:
        _controller: App\Controller\Security\SecurityController::login

adminRegister:
    path: /admin/register
    defaults:
       _controller: App\Controller\Security\RegisterController::register

#adminUsers:
#    path: /admin/users
#    defaults:
#       _controller: App\Controller\Security\UserController::show

adminEditUser:
    path: /admin/user/edit/{id}
    defaults:
        _controller: App\Controller\Admin\UserEditController::edit

adminDeleteUser:
    path: /admin/user/delete/{id}
    defaults:
        _controller: App\Controller\Admin\UserDeleteController::delete

#adminGallery:
#    path: /admin/gallery/{id}
#    defaults:
#        _controller: App\Controller\Admin\Gallery\GalleryAddAddController::show

adminGalleryUpdate:
    path: /admin/gallery/update/{slug}
    defaults:
        _controller: App\Controller\GalleryController::update

adminGalleryDelete:
    path: /admin/gallery/delete/{slug}
    defaults:
        _controller: App\Controller\GalleryController::delete

adminSite:
    path: /admin/interface
    defaults:
        _controller: App\Controller\Admin\InterfaceController::show

#AdminSiteReviews:
#    path: /admin/interface/reviews
#    defaults:
#      _controller: App\Controller\Admin\ReviewsController::addReviews

#adminBenefit:
#    path: /admin/configuration/benefit
#    defaults:
#      _controller: App\Controller\Configuration\BenefitController::show

adminBenefitEdit:
    path: /admin/configuration/benefit/{id}
    defaults:
      _controller: App\Controller\Configuration\BenefitEditController::edit

adminReviews:
    path: /admin/interface/reviews
    defaults:
      _controller: App\Controller\Admin\ReviewsController::show

logout:
    path: /logout